feat: add new rule correct-game-instantiating
dart-code-checker/dart-code-metrics pull request #1163
Opened 2023-01-27 08:43 UTC by incendial

### What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [X] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

2023-01-27 12:46 UTC, spydon commented
Looks good! 🔥

2023-01-29 17:45 UTC, dkrutskikh requested changes

2023-01-29 17:45 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/models/flame_rule.dart
> +/// Represents a base class for Flutter-specific rules.
@incendial maybe `for Flutter Flame Engine` ?

2023-01-29 17:50 UTC, dkrutskikh approved these changes

2023-01-29 17:51 UTC, dkrutskikh approved these changes

2023-01-29 17:52 UTC, merged