feat: add static code diagnostic avoid-initializing-in-on-mount
dart-code-checker/dart-code-metrics pull request #1165
Opened 2023-01-27 13:32 UTC by incendial

### What is the purpose of this pull request? (put an "X" next to an item)

- [ ] Documentation update
- [ ] Bug fix
- [X] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [ ] Add a CLI option
- [ ] Add something to the core
- [ ] Other, please explain:

2023-01-29 18:02 UTC, dkrutskikh requested changes

2023-01-29 18:02 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/models/flame_rule.dart
> +  static const link = 'https://pub.dev/packages/flame';
@incendial unused constant

2023-01-30 19:04 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/models/flame_rule.dart
> +/// Represents a base class for Flutter-specific rules.
Fixed.

2023-01-30 19:04 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/models/flame_rule.dart
> +  static const link = 'https://pub.dev/packages/flame';
Fixed.

2023-01-30 19:07 UTC, dkrutskikh approved these changes

2023-01-30 19:21 UTC, merged