Implement rule avoid-returning-widgets
dart-code-checker/dart-code-metrics pull request #251
Opened 2021-04-06 15:00 UTC by incendial

### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[X] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

2021-04-06 15:24 UTC, GroovinChip commented
VERY happy to see this 🥳

2021-04-10 16:06 UTC, dkrutskikh requested changes

2021-04-10 16:06 UTC, dkrutskikh commented on lib/src/obsoleted/rules/avoid_returning_widgets_rule.dart
> +  static const _warningMessage = 'Avoid returning widgets from a function';
@incendial I think a good idea use the rules of [parallel construction](https://en.wikipedia.org/wiki/Parallelism_(grammar))

2021-04-10 16:06 UTC, dkrutskikh commented on lib/src/obsoleted/rules/avoid_returning_widgets_rule.dart
> +      config.containsKey('ignored-names') && config['ignored-names'] is Iterable
@incendial please extract to constant

2021-04-10 16:06 UTC, dkrutskikh commented on lib/src/obsoleted/rules/avoid_returning_widgets_rule.dart
> +  final List<String> _ignoredNames;
@incendial please use Iterable

2021-04-10 20:00 UTC, incendial commented on lib/src/obsoleted/rules/avoid_returning_widgets_rule.dart
> +  final List<String> _ignoredNames;
Done.

2021-04-10 20:00 UTC, incendial commented on lib/src/obsoleted/rules/avoid_returning_widgets_rule.dart
> +      config.containsKey('ignored-names') && config['ignored-names'] is Iterable
Done.

2021-04-11 10:38 UTC, dkrutskikh approved these changes

2021-04-11 10:41 UTC, merged