Rename all rules config items from snake_case to kebab-case with backward compatibility
dart-code-checker/dart-code-metrics pull request #256
Opened 2021-04-08 20:09 UTC by incendial

### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[ ] New rule
[X] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)
Changes config of prefer-trailing-comma, component-annotation-arguments-ordering and member-ordering.

2021-04-09 21:02 UTC, dkrutskikh requested changes

2021-04-09 21:02 UTC, dkrutskikh commented on lib/src/utils/rule_utils.dart
> +String normalizeRuleConfigItem(String configItem) =>
and please add unit test

2021-04-09 21:06 UTC, incendial commented on lib/src/utils/rule_utils.dart
> +String normalizeRuleConfigItem(String configItem) =>
Are you sure about that? It's more like a rule specific function rather then a generic one.

2021-04-10 10:03 UTC, dkrutskikh approved these changes

2021-04-10 10:11 UTC, merged