Added GitHub reporter steps
dart-code-checker/dart-code-metrics pull request #273
Opened 2021-04-21 14:57 UTC by furaiev

### What is the purpose of this pull request? (put an "X" next to an item)

[ x ] Documentation update

closes https://github.com/dart-code-checker/dart-code-metrics/issues/246

### What changes did you make? (Give an overview)
GitHub reporter documentation

2021-04-21 15:09 UTC, furaiev commented
Just found that it works only if I copy in the root of my project `bin/metrics.dart` from the package. 
Please advise how to adjust the instructions.

2021-04-21 18:18 UTC, dkrutskikh requested changes

2021-04-21 18:18 UTC, dkrutskikh commented on doc/reporters/github-reporter.md
> +```
@furaiev please add empty line before backticks, and add language specification for quoted block

2021-04-21 18:50 UTC, incendial requested changes
First of all, thank you for your contribution. We definitely have some problems with docs and your input is very helpful. If you have some time, I'd suggest to make small improvements to help users even more, but it's okay if you don't have it.

If you don't have time to fix it, just let us know and we will fix the PR by ourselves.

2021-04-21 18:50 UTC, incendial commented on doc/reporters/github-reporter.md
> +1. Your git workflow must include/support flutter/dart
It might be not so clear for the external user what does this phrase mean. Seems like they might expect an example here.

2021-04-21 18:50 UTC, incendial commented on doc/reporters/github-reporter.md
> +        run: flutter pub run dart_code_metrics:metrics lib --reporter=github lib
This works if the project is added to `dev_dependencies` , but it seems that we should also cover a case when the project is installed as a global dependency.

2021-04-22 03:32 UTC, dkrutskikh approved these changes

2021-04-22 19:30 UTC, incendial approved these changes

2021-04-22 19:33 UTC, merged