Add avoid `late` keyword rule.
dart-code-checker/dart-code-metrics pull request #284
Opened 2021-04-25 15:59 UTC by incendial

### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[X] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

2021-04-25 18:01 UTC, dkrutskikh approved these changes

2021-04-26 20:02 UTC, dkrutskikh requested changes

2021-04-26 20:02 UTC, dkrutskikh commented on lib/src/obsoleted/rules/avoid_late_keyword.dart
> +                withCommentOrMetadata: true,
@incendial please remove this line

2021-04-26 21:07 UTC, incendial commented on lib/src/obsoleted/rules/avoid_late_keyword.dart
> +                withCommentOrMetadata: true,
Done.

2021-04-27 02:39 UTC, dkrutskikh approved these changes

2021-04-27 02:39 UTC, merged