feat: add Avoid unnecessary setstate
dart-code-checker/dart-code-metrics pull request #346
Opened 2021-05-18 18:47 UTC by incendial

### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[X] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)
Closes #332

2021-05-24 12:57 UTC, dkrutskikh requested changes

2021-05-24 12:57 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
> +          .toList(growable: false),
@incendial please remove unnecessary toList.

2021-05-24 12:57 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
> +          .toList(growable: false)
@incendial please remove unnecessary toList.

2021-05-24 12:57 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
> +            brief: 'Warns ',
@incendial please add more detailed message

2021-05-26 12:06 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
> +          .toList(growable: false)
Done.

2021-05-26 12:06 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
> +            brief: 'Warns ',
Done.

2021-05-26 12:06 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_setstate/avoid_unnecessary_setstate.dart
> +          .toList(growable: false),
Done.

2021-05-26 21:05 UTC, dkrutskikh approved these changes

2021-05-26 21:05 UTC, merged