Prefer matching widget file name
dart-code-checker/dart-code-metrics pull request #410
Opened 2021-07-27 21:34 UTC by Konoshenko

### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[X] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

2021-07-31 07:47 UTC, dkrutskikh requested changes

2021-07-31 07:47 UTC, dkrutskikh commented on README.md
> +src="https://raw.githubusercontent.com/dart-code-checker/dart-code-metrics/master/doc/.assets/logo.svg"
@Konoshenko please revert all changes in this file

2021-07-31 07:47 UTC, dkrutskikh commented on test/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/examples/example.dart
> +class Example extends StatelessWidget {
@Konoshenko please add examples with statefullwidget

2021-07-31 07:47 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/prefer_match_file_name.dart
> +import 'package:analyzer/dart/ast/ast.dart';
@Konoshenko please add your rule in rules_factory

2021-07-31 07:47 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/visitor.dart
> +  String getFileName(String filePath) =>
@Konoshenko please use `path` package

2021-07-31 07:50 UTC, dkrutskikh commented
@Konoshenko first of all - thank you for contribute. Please take a look at review notes.

2021-08-01 11:58 UTC, dkrutskikh requested changes

2021-08-01 11:58 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/rules_factory.dart
> +import 'package:dart_code_metrics/src/analyzers/lint_analyzer/rules/rules_list/prefer_match_file_name/prefer_match_file_name.dart';
@Konoshenko please use relative import

2021-08-03 07:55 UTC, dkrutskikh approved these changes

2021-08-03 13:00 UTC, incendial requested changes
Thank you for a great work! Left some small comments.

2021-08-04 06:25 UTC, dkrutskikh approved these changes

2021-08-04 06:36 UTC, incendial approved these changes

2021-08-04 18:26 UTC, merged