Update const border radius rule
dart-code-checker/dart-code-metrics pull request #482
Opened 2021-09-30 16:15 UTC by grafovdenis

### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[ ] New rule
[x] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)
* Update doc
* Update test example
* Update test
* Update rule visitor

### Is there anything you'd like reviewers to focus on?

2021-09-30 17:35 UTC, dkrutskikh requested changes

2021-09-30 17:35 UTC, dkrutskikh commented on lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/visitor.dart
> +        // TODO(grafov): check result of binary expression
@grafovdenis please remove this TODO

2021-10-01 19:01 UTC, dkrutskikh approved these changes

2021-10-03 08:29 UTC, incendial requested changes
Thanks for the rule update. Added several small comments.

2021-10-03 08:29 UTC, incendial commented on CHANGELOG.md
> +* feat: Update static code diagnostic `prefer-const-border-radius`.
Since we didn't release the rule yet, we don't need to mention the rule change.

2021-10-03 08:29 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/prefer_const_border_radius.dart
> +      'Prefer to use const constructor BorderRadius.all.';
Let's have either `Prefer using const constructor BorderRadius.all` or `Prefer const constructor BorderRadius.all.`. We don't use `to use` in any other rule.

2021-10-03 08:29 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/visitor.dart
> +const borderRadiusConstructorName = 'circular';
Please make these variables private.

2021-10-03 08:29 UTC, incendial commented on test/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/examples/example.dart
> +import 'flutter_define.dart';
Let's keep all the rule code in the example file.

2021-10-03 08:29 UTC, incendial commented on test/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/examples/example.dart
> +      ClipRRect(borderRadius: BorderRadius.circular(_constValue - _finalValue)),
Could you add test cases for conditional expression as `BorderRadius` argument and for method invocation as argument?

2021-10-03 08:29 UTC, incendial commented on test/analyzers/lint_analyzer/rules/rules_list/prefer_const_border_radius/prefer_const_border_radius_test.dart
> +          startLines: [4, 9, 12, 13, 17, 22],
I see seven `// LINT` comments and only 6 actual triggers (line 25 doesn't trigger the rule). Please update the test file.

2021-10-04 09:19 UTC, incendial approved these changes

2021-10-04 09:49 UTC, merged