feat: add static code diagnostics `avoid-unnecessary-type-assertions`
dart-code-checker/dart-code-metrics pull request #549
Opened 2021-11-09 17:46 UTC by Konoshenko

### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[ ] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)

### Is there anything you'd like reviewers to focus on?

2021-11-10 19:14 UTC, dkrutskikh approved these changes

2021-11-11 05:44 UTC, dkrutskikh requested changes

2021-11-11 09:49 UTC, dkrutskikh approved these changes

2021-11-11 10:20 UTC, incendial requested changes

2021-11-11 10:20 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/rules_list/avoid_unnecessary_type_assertions/avoid_unnecessary_type_assertions.dart
> +            message: 'Avoid redundant "${node.value}" assertion.',
My bad, let's replace `redundant` with `unnecessary`.

2021-11-11 10:20 UTC, incendial commented on website/docs/rules/common/avoid-unnecessary-type-assertions.md
> +Warns about of unnecessary use of comparison operators 'is' and 'whereType'.
Warns about unnecessary usage of 'is' and 'whereType' operators.

2021-11-11 10:20 UTC, incendial commented on website/docs/rules/overview.md
> +    Warns about of unnecessary use of comparison operators 'is' and 'whereType'.
Warns about unnecessary usage of 'is' and 'whereType' operators.

2021-11-11 14:57 UTC, incendial approved these changes

2021-11-11 17:07 UTC, merged