feat: add content section in readme file
dart-code-checker/dart-code-metrics pull request #596
Opened 2021-12-10 17:33 UTC by Konoshenko

[X] Documentation update
[ ] Bug fix
[ ] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

### What changes did you make? (Give an overview)
Add content section in readme

2021-12-10 22:00 UTC, dkrutskikh requested changes

2021-12-10 22:00 UTC, dkrutskikh commented on README.md
> +###En
```suggestion
### En
```

missed space

2021-12-10 22:00 UTC, dkrutskikh commented on README.md
> +###Ru
```suggestion
### Ru
```

missed space

2021-12-11 12:27 UTC, incendial commented on README.md
> +## Written Resources
```suggestion
## Articles
```

2021-12-12 05:22 UTC, dkrutskikh approved these changes

2021-12-12 12:33 UTC, incendial approved these changes

2021-12-12 14:19 UTC, merged