feat: add prefer-async-await rule
dart-code-checker/dart-code-metrics pull request #686
Opened 2022-02-06 12:42 UTC by incendial

### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Documentation update
[ ] Bug fix
[X] New rule
[ ] Changes an existing rule
[ ] Add autofixing to a rule
[ ] Add a CLI option
[ ] Add something to the core
[ ] Other, please explain:

2022-02-06 12:43 UTC, incendial commented
@roman-petrov could you please take a look too? Maybe I missed some cases.

2022-02-06 13:56 UTC, roman-petrov commented
@incendial this looks promising! I am a bit ill and surely will take closer look in a couple of days.

2022-02-07 11:32 UTC, incendial commented
> @incendial this looks promising! I am a bit ill and surely will take closer look in a couple of days.

Sure, get well soon!

2022-02-07 13:51 UTC, dkrutskikh requested changes

2022-02-07 16:26 UTC, incendial commented on lib/src/analyzers/lint_analyzer/rules/rules_list/prefer_async_await/prefer_async_await_rule.dart
> +                withCommentOrMetadata: true,
Fixed

2022-02-07 16:51 UTC, dkrutskikh approved these changes

2022-02-07 16:51 UTC, merged